name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pipenv
        pipenv install

    - name: Run Tests
      run: |
        pipenv run python manage.py test



# name: Django CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest
#     strategy:
#       max-parallel: 4
#       matrix:
#         python-version: [3.9,3.11]

#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up Python ${{ matrix.python-version }}
#       uses: actions/setup-python@v3
#       with:
#         python-version: ${{ matrix.python-version }}
#     - name: Copy Pipfile
#       run: cp ../Pipfile .
#     - name: Install Dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install --upgrade pipenv
#         pipenv install  
#     - name: Activate virtual environment
#       run: |
#         pipenv shell
#     - name: Run Tests
#       run: |
#         python manage.py test
